quarkus.datasource.jdbc.url=${DB_URL}
quarkus.datasource.username=${DB_USERNAME}
quarkus.datasource.password=${DB_PASSWORD}

quarkus.hibernate-orm.schema-management.strategy=update

quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.path=/docs